# Generated by Django 5.0.2 on 2024-03-09 20:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.IntegerField(max_length=40)),
                ('cuerpo', models.TextField()),
                ('fecha', models.DateTimeField(default=datetime.date(2024, 3, 9))),
            ],
        ),
    ]
